include: package:flutter_lints/flutter.yaml

linter:
  rules:
    # Disable untuk sementara karena sudah ada mounted check manual
    use_build_context_synchronously: false

analyzer:
  errors:
    # Tetap tampilkan sebagai info saja, bukan error
    use_build_context_synchronously: info