// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDRssnH1E1QOdbfRJtLXO8dcyo6ktsGhmQ',
    appId: '1:112282417853:web:4c2b46e4c94fbe7bd355d4',
    messagingSenderId: '112282417853',
    projectId: 'clean-office-app',
    authDomain: 'clean-office-app.firebaseapp.com',
    storageBucket: 'clean-office-app.firebasestorage.app',
    measurementId: 'G-4KF0L88D97',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBcD90mzDgYTkiOQFsshIZof1oI3roDIHM',
    appId: '1:112282417853:android:327e339ae3bbef9bd355d4',
    messagingSenderId: '112282417853',
    projectId: 'clean-office-app',
    storageBucket: 'clean-office-app.firebasestorage.app',
  );
}
